Resources:
  CategoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.serviceResource}-CategoryTable-${self:provider.stage}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
        - AttributeName: category
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
        - AttributeName: category
          KeyType: RANGE

  TransactionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.serviceResource}-TransactionTable-${self:provider.stage}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
